### ISSUE TITLE
Would it be possible to have recommended default settings?

### ISSUE THREAD

**Issue by CGCooke** [facebookresearch/silk#11]
Hi,

SuperGlue provides some default settings that work well.

For example:

_For indoor images, we recommend the following settings (these are the defaults):
./match_pairs.py --resize 640 --superglue indoor --max_keypoints 1024 --nms_radius 4

For outdoor images, we recommend the following settings:
./match_pairs.py --resize 1600 --superglue outdoor --max_keypoints 2048 --nms_radius 3 --resize_flo_

Would it be possible to have something similar documented?

This might help people get the best performance "out of the box".

**Comment by gleize** [comment]
Hi @CGCooke,

Yes, initially I wanted to make a similar command line tool with all parameters exposed, but because of lack of time, I only provided an example scripts with default parameters in code [here](https://github.com/facebookresearch/silk/blob/09ded25ec7673ce2084996a2376ccf7b54e1c87d/scripts/examples/common.py).

I'll add this tool and some doc as soon as I get some cycle.

**Comment by gleize** [comment]
Hi @CGCooke,

I've added CLI tools with default parameters (c.f. [here](https://github.com/facebookresearch/silk/blob/main/doc/usage/inference.md#cli-tools)). This should get good result "out of the box", regardless of whether the images are taken inside or outside.
That being said, we also advise tuning those parameters (c.f. [here](https://github.com/facebookresearch/silk/blob/main/doc/usage/faq.md#how-to-tune-silk-)) for improved performance on specific tasks.
