### ISSUE TITLE
how to prepare the environment in windows

### ISSUE THREAD

**Issue by 52THANOS** [facebookresearch/silk#32]
i have a  hard time in pip install -e .

**Comment by 52THANOS** [comment]
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///D:/DownloadProject/silk
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error: supposed package directory 'silk' exists, but is not a directory
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by gleize** [comment]
Hi @52THANOS,

This error is similar to https://github.com/facebookresearch/silk/issues/31.
The symlink seems to cause an issue on some OS. This can be solved by either re-creating the symlink on your OS, or by hard-copying the directory `lib` to `silk` (ugly but should work).

Since I do not use Windows OS, I do not know the exact steps, but following the above suggestions are likely to resolve your issue.

**Comment by 52THANOS** [comment]
problem solved
