### ISSUE TITLE
SiLK performed poor when input image has a small resolution

### ISSUE THREAD

**Issue by yueyunqingwu** [facebookresearch/silk#38]
I trained Silk with default input size of 164x164, in inference stage, SiLK performed poor when input image has a small resolution, e.g. 30x30, I got only 3-4 pairs of matched keypoints. How to explain and fix it?

**Comment by gleize** [comment]
Hi @yueyunqingwu,

Difficult to figure out the exact problem without additional information, but here are a few thought as to why the performance could be low in your case.

* Does the small image have enough identifiable texture ? (corners, line intersection, etc). Or is it closer to a uniform patch ?
* The default backbone doesn't use padding. So it means that your 30x30 image will produce a 12x12 feature map. This is quite small, and might not work if there are not enough distinctive features in the image.
* In images with resolution 640x480, 10,000 keypoints is enough to get good matching performance. It represents about 3% of the total pixels. In your case, 3-4 matches represents about 2.5% of the total pixels (in feature space). So that's not very different. It's just that your resolution is quite smaller than more common use cases.

If you can run the model on a higher resolution (or even up-sample your 30x30 images), this should result in more matches.

**Comment by yueyunqingwu** [comment]
@gleize Thank you for your reply. I will try what you suggested.
