### ISSUE TITLE
Question regarding small batch size.

### ISSUE THREAD

**Issue by mertkaraoglu** [facebookresearch/silk#4]
Hi, thank you for the paper, it is very much inspiring. Can you please explain why the batch size is chosen to be 1 (per GPU)? I presume this is not due to lack of vRAM.

**Comment by gleize** [comment]
Hi @mertkaraoglu,

We are limited in vRAM by the similarity matrix. That matrix has size `(HW)x(HW)`, which is quite large to process and backprop through.

In order to tackle that challenge, we had to implement a custom backprop that processes the matrix in "blocks" and re-compute those blocks during backprop instead of storing them. Similar to this [paper](https://arxiv.org/abs/2112.05682).

**Comment by mertkaraoglu** [comment]
Thank you for the detailed reply.
