### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by zhangsngood** [facebookresearch/silk#43]
Hi, when testing, I was hoping to get a visualization similar to the Figure 1 in your article.
![silk_matching](https://github.com/facebookresearch/silk/assets/115128549/3282c794-9f12-40a2-accd-cbfbd0a38dc5)

**Comment by zhangsngood** [comment]
But when I run the test code, I get the following visualization of the matches. I found that the color of the matching line in this way is not conducive to interpreting whether the matching result is good or bad. Can you please tell me how I can show the result like Figure 1.
![out_image](https://github.com/facebookresearch/silk/assets/115128549/13c4cb5d-08e6-4c4d-8766-639ccf809746)

**Comment by gleize** [comment]
Hi @zhangsngood,

The visualization produced in the paper uses that [function](https://github.com/facebookresearch/silk/blob/aa51cd46899346cfa2873bbc06d6e11c6b9d92f7/lib/cli/hpatches_tests.py#L89).
In order to get the green / red colors for correct / incorrect matches, you need to provide ground truth matches (`good_matches_mask` argument). Since the inference code we provide doesn't have any ground truth (you can use any pair of images), we do show different colors in order to "manually" check if the correspondences are correct or not.

Looking at your image, the correspondences seems to look good, false positive matches would visually result in a lot of line crossing. To be certain of the quality, you would have to compute some metrics, using ground truth data (mean matching accuracy, homography estimation accuracy) or looking at the reconstruction statistics (number of registered images, re-projection error, etc).

**Comment by gleize** [comment]
Inactive for the last three weeks. Closing now.
