### ISSUE TITLE
Where is matching probabilities and matching success calculated

### ISSUE THREAD

**Issue by akimihiro** [facebookresearch/silk#47]
I am looking for specific code that implements the calculation of matching probabilities and matching success, but I'm having a hard time finding it. It seemed to me that the self._model.coordinate_mapping_composer.get function in SiLKRandomHomographies within lib/models/silk.py does it. However, upon examining the model.coordinate_mapping_composer.get function, I still cannot find the specific code where the calculation is implemented.

**Comment by gleize** [comment]
Hi @akimihiro,

The coordinate mapper doesn't handle the matching, it handles the coordinate change between the feature space and the input space (because the feature spatial dimensions are downsampled).
The matching probabilities can be found two places :
* During **training**, the matching probabilities are computed in log space and implemented [here](https://github.com/facebookresearch/silk/blob/aa51cd46899346cfa2873bbc06d6e11c6b9d92f7/lib/losses/info_nce/loss.py#L120). Regarding the matching success, we first extract the best prediction of the model [here](https://github.com/facebookresearch/silk/blob/aa51cd46899346cfa2873bbc06d6e11c6b9d92f7/lib/losses/info_nce/loss.py#L262-L263) and test if they are a success [here](https://github.com/facebookresearch/silk/blob/aa51cd46899346cfa2873bbc06d6e11c6b9d92f7/lib/losses/info_nce/loss.py#L196-L197).
* During **inference**, the matching probabilities are computed [here](https://github.com/facebookresearch/silk/blob/aa51cd46899346cfa2873bbc06d6e11c6b9d92f7/lib/matching/mnn.py#L38).

**Comment by akimihiro** [comment]
Thank you very much for your response! It successfully resolved my issue. I appreciate the time and effort you took to help me out. Your clear explanation made it easy for me to understand the code. Thanks again!
