### ISSUE TITLE
coco trainning data

### ISSUE THREAD

**Issue by egbertYeah** [facebookresearch/silk#48]
for pvgg-4.ckpt file, i am very confused as to whether the entire coco was used for the training data or only 1,000 images.  
I found some clues below, so asked to verify.
<img width="462" alt="image" src="https://github.com/facebookresearch/silk/assets/39177405/5838be2e-4270-438b-bc96-ded090894265">
`trainer:
  max_epochs: 100
  limit_val_batches: 100
  limit_train_batches: 1000
`

**Comment by gleize** [comment]
Hi @egbertYeah,

We do indeed limit the training epochs to 1000 images in order to speed-up the training. Images are randomly sampled at each epoch. So, statistically speaking, it covers a large portion of the COCO dataset.
Unlike object detection / recognition, SiLK doesn't need that large of a dataset since the models it uses are low-capacity, and each image we train on contain a large amount of potential keypoints (128x128 per image).
