### ISSUE TITLE
superpoint training-phase-1.h5 and superpoint training-phase-2.h5 

### ISSUE THREAD

**Issue by ShuWzp** [facebookresearch/silk#53]
Hello respected author, your work is excellent. I have a few questions. What are superpoint training-phase-1.h5 and superpoint training-phase-2.h5 in your code? If I want to use my own medical data, how can I obtain these files?

**Comment by AliYoussef97** [comment]
@ShuWzp If I'm not mistaken the answer could be found in this markdown [file](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/doc/models/SUPERPOINT.md)

I believe superpoint training-phase-1.h5 contains the COCO dataset pseudo ground truth feature labels/points extracted using MagicPoint used to train the SuperPoint model, resulting in "superpoint-phase-1" model.

The trained model "superpoint-phase-1" is then used to extract pseudo ground truth feature labels/points on the COCO dataset for the next training phase, where the data is saved in training-phase-2.h5, and the SuperPoint model is trained once more on data saved in training-phase-2.h5; however, I could be wrong.

If you would like to use your own medical data, you could follow the steps [here](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/doc/models/SUPERPOINT.md) (You can skip step 1 and 2), for step 3 and 7 instead of "Homographically augment COCO dataset (phase 1)" and Homographically augment COCO dataset (phase 2), you will perform homographic augmentation on your own dataset for example:

          3-Homographically augment Medical Images dataset (phase 1)

          7-Homographically augment Medical Images dataset (phase 2). 

I hope the information stated was correct, the authors can correct me if I am wrong of course.

**Comment by ShuWzp** [comment]
It seems that I understand you. When my medical images do not have keypoint labels, can I use MagicPoint for detection? Since most of my images are blood vessels, it should be possible to utilize MagicPoint for detection.

**Comment by ShuWzp** [comment]
> @ShuWzp If I'm not mistaken the answer could be found in this markdown [file](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/doc/models/SUPERPOINT.md)
> 
> I believe superpoint training-phase-1.h5 contains the COCO dataset pseudo ground truth feature labels/points extracted using MagicPoint used to train the SuperPoint model, resulting in "superpoint-phase-1" model.
> 
> The trained model "superpoint-phase-1" is then used to extract pseudo ground truth feature labels/points on the COCO dataset for the next training phase, where the data is saved in training-phase-2.h5, and the SuperPoint model is trained once more on data saved in training-phase-2.h5; however, I could be wrong.
> 
> If you would like to use your own medical data, you could follow the steps [here](https://github.com/facebookresearch/silk/blob/0e5a823a5e635b171ab908353dcb6e0a573fd58d/doc/models/SUPERPOINT.md) (You can skip step 1 and 2), for step 3 and 7 instead of "Homographically augment COCO dataset (phase 1)" and Homographically augment COCO dataset (phase 2), you will perform homographic augmentation on your own dataset for example:
> 
> ```
>       3-Homographically augment Medical Images dataset (phase 1)
> 
>       7-Homographically augment Medical Images dataset (phase 2). 
> ```
> 
> I hope the information stated was correct, the authors can correct me if I am wrong of course.

It seems that I understand you. When my medical images do not have keypoint labels, can I use MagicPoint for detection? Since most of my images are blood vessels, it should be possible to utilize MagicPoint for detection.

**Comment by AliYoussef97** [comment]
> It seems that I understand you. When my medical images do not have keypoint labels, can I use MagicPoint for detection? Since most of my images are blood vessels, it should be possible to utilize MagicPoint for detection.

You can certainly just use MagicPoint for detection, SuperPoint's keypoints are much more repeatable so it is worth taking the extra steps to train it.

It is important to note that both MagicPoint and SuperPoint are trained as corner detectors, and if the blood vessel images lack corners, then both MagicPoint and SuperPoint might not be the best choice for feature detection, SiLK would be the better choice since it aims to learn keypoints without defining them as corners.

**Comment by ShuWzp** [comment]
> > It seems that I understand you. When my medical images do not have keypoint labels, can I use MagicPoint for detection? Since most of my images are blood vessels, it should be possible to utilize MagicPoint for detection.
> 
> You can certainly just use MagicPoint for detection, SuperPoint's keypoints are much more repeatable so it is worth taking the extra steps to train it.
> 
> It is important to note that both MagicPoint and SuperPoint are trained as corner detectors, and if the blood vessel images lack corners, then both MagicPoint and SuperPoint might not be the best choice for feature detection, SiLK would be the better choice since it aims to learn keypoints without defining them as corners.

I understand now, thank you for patiently answering.

**Comment by gleize** [comment]
Thanks @AliYoussef97 for answering.

@ShuWzp Since you are working on medical images, there is an interesting paper for you called [RIDE](https://arxiv.org/pdf/2309.09563.pdf). They've re-trained SiLK on medical images and also added an additional component to handle large in-plane rotations (if that's an issue for you as well). They've obtained SOTA results on medical image benchmarks. @mertkaraoglu is the first author of that paper and might be able to give you some insights.
