### ISSUE TITLE
did you test superglue with silk?

### ISSUE THREAD

**Issue by egbertYeah** [facebookresearch/silk#54]
In order to get better results, I tried to replace MNN with super glue, but found that the effect on badcase was not improved.

I re-read the paper and found that there is no experiment on silk+superglue, so I would like to ask whether replacing the matcher has little impact on the effect of silk?

**Comment by gleize** [comment]
Hi @egbertYeah,

Sorry for the late reply. We haven't tried SiLK + SuperGlue, we left it for future work in order to keep the base model "simple".

I'm surprised about your results though, have you trained the context aggregator in the same way as described in the SuperGlue paper ? Did you use the same data, positional encoding method and freeze the descriptors ?

If you trained it on random homography, it might be a case of "homography over-fitting" (since the receptive field would grow drastically). It would likely benefit from using the exact SuperGlue training methodology.

**Comment by egbertYeah** [comment]
@gleize hello, i trained superglue with silk. to save resources, top_k is set to 1000, and other parameters remain unchanged. However, the PR on the same test set is relatively poor. i got P=56.03, R=65.08, the superglue repository i used is https://github.com/gouthamvgk/SuperGlue_training/tree/main, P=80.87, R=96.22.
<img width="597" alt="image" src="https://github.com/facebookresearch/silk/assets/39177405/59bce365-f4e9-48d4-9620-a5b49c12486d">

**Comment by egbertYeah** [comment]
I also found a problem. The quality of the key points extracted by silk may not be high. The keypoint matching number entered into the findHomography function may have a good matching result when it is greater than 50, but 20 for superpoints are enough.

**Comment by gleize** [comment]
Hi @egbertYeah,

Sorry for the late reply. Just came back from a long vacation.
Regarding your SuperGlue + SiLK results, thanks for sharing. I just have a few questions.

* Have you been able to reproduce the SuperGlue + SuperPoint results ? (just to make sure the training pipeline isn't misconfigured or different python dependencies might affect results).

From your second comment (from what I understand), you're saying that the SiLK version requires more good matches to work well ? While a fewer number is necessary for SuperPoint ?
That could very well be the case since SiLK tends to generate a lot more keypoint candidates than SuperPoint (since SuperPoint does a factor-8 downsampling), but then it produces less keypoint overlap (i.e. the keypoint score rank is not conserved very well).
I'm wondering if you have tried increasing the number of SiLK keypoints ? Or tried some intermediate filtering ? (e.g. do a 10k x 10k simple cosine computation, take the best 1k matches, and feed those best keypoints to SuperGlue). This should eliminate a lot of the non-overlapping keypoints and get a bit more good matches for the final estimate.

Would it be possible to share your code about the SiLK integration you've done in the [SuperGlue codebase](https://github.com/gouthamvgk/SuperGlue_training/tree/main) ? 

Thanks.
